/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestNewRouteImport } from './routes/request.new'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as OnboardingWorkerRouteImport } from './routes/onboarding.worker'
import { Route as OnboardingDriverRouteImport } from './routes/onboarding.driver'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminBootstrapRouteImport } from './routes/admin/bootstrap'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNewRoute = RequestNewRouteImport.update({
  id: '/request/new',
  path: '/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkerRoute = OnboardingWorkerRouteImport.update({
  id: '/onboarding/worker',
  path: '/onboarding/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDriverRoute = OnboardingDriverRouteImport.update({
  id: '/onboarding/driver',
  path: '/onboarding/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/request/$id': typeof RequestIdRoute
  '/request/new': typeof RequestNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/request/$id': typeof RequestIdRoute
  '/request/new': typeof RequestNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/request/$id': typeof RequestIdRoute
  '/request/new': typeof RequestNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/support'
    | '/terms'
    | '/admin/bootstrap'
    | '/admin/monitoring'
    | '/admin/subscriptions'
    | '/onboarding/driver'
    | '/onboarding/worker'
    | '/request/$id'
    | '/request/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/support'
    | '/terms'
    | '/admin/bootstrap'
    | '/admin/monitoring'
    | '/admin/subscriptions'
    | '/onboarding/driver'
    | '/onboarding/worker'
    | '/request/$id'
    | '/request/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/support'
    | '/terms'
    | '/admin/bootstrap'
    | '/admin/monitoring'
    | '/admin/subscriptions'
    | '/onboarding/driver'
    | '/onboarding/worker'
    | '/request/$id'
    | '/request/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  OnboardingDriverRoute: typeof OnboardingDriverRoute
  OnboardingWorkerRoute: typeof OnboardingWorkerRoute
  RequestIdRoute: typeof RequestIdRoute
  RequestNewRoute: typeof RequestNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/new': {
      id: '/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof RequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/worker': {
      id: '/onboarding/worker'
      path: '/onboarding/worker'
      fullPath: '/onboarding/worker'
      preLoaderRoute: typeof OnboardingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/driver': {
      id: '/onboarding/driver'
      path: '/onboarding/driver'
      fullPath: '/onboarding/driver'
      preLoaderRoute: typeof OnboardingDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bootstrap': {
      id: '/admin/bootstrap'
      path: '/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBootstrapRoute: AdminBootstrapRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoleRoute: SelectRoleRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  OnboardingDriverRoute: OnboardingDriverRoute,
  OnboardingWorkerRoute: OnboardingWorkerRoute,
  RequestIdRoute: RequestIdRoute,
  RequestNewRoute: RequestNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
